/// @author Alexander Rykovanov 2013
/// @email rykovanov.as@gmail.com
/// @brief Well known attributes identifiers.
/// @license GNU LGPL
///
/// Distributed under the GNU LGPL License
/// (See accompanying file LICENSE or copy at
/// http://www.gnu.org/licenses/lgpl.html)
///

#ifndef __OPC_UA_BINARY_IDENTIFIERS
#define __OPC_UA_BINARY_IDENTIFIERS

#include <stdint.h>

namespace OpcUa
{
  enum class ObjectID : uint32_t
  {
    Null           = 0,
    Boolean        = 1,
    SByte          = 2,
    Byte           = 3,
    Int16          = 4,
    UInt16         = 5,
    Int32          = 6,
    UInt32         = 7,
    Int64          = 8,
    UInt64         = 9,
    Float          = 10,
    Double         = 11,
    String         = 12,
    DateTime       = 13,
    Guid           = 14,
    ByteString     = 15,
    XmlElement     = 16,
    NodeID         = 17,
    ExpandedNodeID = 18,
    StatusCode     = 19,
    QualifiedName  = 20,
    LocalizedText  = 21,
    Structure      = 22,
    DataValue      = 23,
    BaseDataType   = 24,
    DiagnosticInfo = 25,
    Number         = 26,
    Integer        = 27,
    UInteger       = 28,
    Enumeration    = 29,
    Image          = 30,
    References     = 31,
    NonHierarchicalReferences = 32,
    HierarchicalReferences = 33,
    HasChild       = 34,
    Organizes      = 35,
    HasEventSource = 36,
    HasModellingRule = 37,
    HasEncoding    = 38,
    HasDescription = 39,
    HasTypeDefinition = 40,
    GeneratesEvent = 41,
    Aggregates     = 44,
    HasSubtype     = 45,
    HasProperty    = 46,
    HasComponent   = 47,
    HasNotifier    = 48,
    HasOrderedComponent = 49,
    HasModelParent = 50,
    FromState      = 51,
    ToState        = 52,
    HasCause       = 53,
    HasEffect      = 54,
    HasHistoricalConfiguration = 56,
    HasHistoricalEventConfiguration = 57,
    BaseObjectType = 58,
    FolderType     = 61,
    BaseVariableType = 62,
    BaseDataVariableType = 63,
    PropertyType   = 68,
    DataTypeDescriptionType = 69,
    DataTypeDictionaryType = 72,
    DataTypeSystemType = 75,
    DataTypeEncodingType = 76,
    ModellingRuleType = 77,
    ModellingRuleMandatory = 78,
    ModellingRuleMandatoryShared = 79,
    ModellingRuleOptional = 80,
    ModellingRuleCardinalityRestriction = 82,
    ModellingRuleExposesItsArray = 83,
    RootFolder     = 84,
    ObjectsFolder  = 85,
    Server  = 2253,
    TypesFolder    = 86,
    ViewsFolder    = 87,
    ObjectTypes    = 88,
    VariableTypes  = 89,
    DataTypes      = 90,
    ReferenceTypes = 91,
    NamingRule     = 111,
    HasSubStateMachine = 117,
    HasEventHistory = 118,
    IdType         = 256,
    NodeClass      = 257,
    Duration       = 290,
    NumericRange   = 291,
    UtcTime        = 294,
    LocaleID       = 295,
    StructureArgument       = 296,
    StructureStatusResult   = 299,
    MessageSecurityMode = 302,
    StructureApplicationDescription = 308,
    SecurityTokenRequestType = 315,
    StructureUserIdentifyToken = 316,
    AnonymousIdentifyToken = 319,
    UserNameIdentifyToken = 322,
    X509IdentifyToken = 325,
    StructureBuildInfo      = 338,
    SoftwareCertificate = 341,
    StructureSignedSoftwareCertificate = 344,
    StructureAddNodesItem   = 376,
    StructureAddReferencesItem = 379,
    StructureDeleteNodesItem = 382,
    StructureDeleteReferencesItem = 385,

    DataChangeNotification = 811,
    EventNotificationList = 812,
    StatusChangeNotification = 813,

    RedundancySupport = 851,
    ServerState    = 852,
    StructureSamplingIntervalDiagnosticsDataType = 856,
    StructureServerDiagnosticsSummaryType = 859,
    StructureServerStatusDataType = 862,
    StructureSessionDiagnosticsDataType = 865,
    StructureSessionSecurityDiagnosticsDataType = 868,
    StructureServiceCounterDataType = 871,
    StructureSubscriptionDiagnosticsDataType = 874,
    StructureModelChangeStructureDataType = 877,
    StructureRange          = 884,
    StructureEUInformation  = 887,
    StructureSemanticChangeStructureDataType = 897,
    ImageBmp       = 2000,
    ImageGif       = 2001,
    ImageJpg       = 2002,
    ImagePng       = 2003,
    ServerType     = 2004,
    ServerArray    = 2254,
    NamespaceArray = 2255,
    ServerStatus   = 2256,
    ServiceLevel   = 2008,
    ServerCapabilities = 2009,
    ServerDiagnostics = 2010,
    VendorServerInfo = 2011,
    ServerRedundancy = 2012,
    ServerCapabilitiesType = 2013,
    ServerProfileArray = 2014,
    LocaleIDArray  = 2016,
    MinSupportedSampleRate = 2017,
    ModellingRules  = 2019,
    ServerDiagnosticsType = 2020,
    ServerDiagnosticsSummary = 2021,
    SamplingIntervalDiagnosticsArray = 2022,
    SubscriptionDiagnosticsArray = 2023,
    EnableFlag      = 2025,
    SessionDiagnosticsSummaryType = 2026,
    SessionDiagnosticsObjectType = 2029,
    VendorServerInfoType = 2033,
    ServerRedundancyType = 2034,
    RedundancySupportTypeRedundancySupport = 2035,
    BaseEventType  = 2041,
    EventID        = 2042,
    EventType      = 2043,
    SourceNode     = 2044,
    SourceName     = 2045,
    Time           = 2046,
    ReceiveTime    = 2047,
    Message        = 2050,
    Severity       = 2051,
    SystemEventType = 2130,
    DeviceFailureEventType = 2131,
    BaseModelChangeEventType = 2132,
    ServerVendorCapabilityType = 2137,
    ServerStatusType = 2138,
    ServerDiagnosticsSummaryType = 2150,
    SamplingIntervalDiagnosticsArrayType = 2164,
    SamplingIntervalDiagnosticsType = 2165,
    SubscriptionDiagnosticsArrayType = 2171,
    SubscriptionDiagnosticsType = 2172,
    SessionsDiagnosticsArrayType = 2196,
    ServerDiagnosticsVariableType = 2197,
    SessionSecurityDiagnosticsArrayType = 2243,
    SessionSecurityDiagnosticsType = 2244,
    StateType      = 2307,
    StateNumber    = 2308,
    TransitionType = 2310,
    HistoricalEventConfigurationType = 2329,
    MaxBrowseContinuationPoints = 2732,
    MaxHistoryContinuationPoints = 2734,
    SemanticChangeEventType = 2738,
    Auditing       = 2742,
    SessionsDiagnosticsSummary = 2744,
    AggregateFunctions = 2754,
    RefreshStartEventType = 2787,
    RefreshEndEventType = 2788,
    RefreshRequiredEventType = 2789,
    EventTypes     = 3048,
    SoftwareCertificates = 3049,
    AlwaysGeneratesEvent = 3065,
    StartTime      = 3074,
    CurrentTime    = 2258,
    State          = 2259,
    BuildInfo      = 3077,
    ProductURI     = 3078,
    ManufacturerName = 3079,
    ProductName    = 3080,
    SoftwareVersion = 3081,
    BuildNumber    = 3082,
    BuildDate      = 3083,
    SecondsTillShutdown = 2992,
    ShutdownReason = 2993,
    LocalTime      = 3190,
    IdTypeEnumStrings = 7591,
    MessageSecurityModeEnumStrings = 7595,
    SecurityTokenRequestTypeEnumStrings = 7598,
    RedundancySupportEnumStrings = 7611,
    ServerStateEnumStrings = 7612,
    HasTrueSubState = 9004,
    HasFalseSubState = 9005,
    HasCondition   = 9006,
  };
}

#endif // __OPC_UA_BINARY_IDENTIFIERS
